name: VueTwitter format

on:
  push:
  pull_request:

jobs:
  prettier:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: 'vue_twitter'

    strategy:
      matrix:
        node-version: [19.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: "vue_twitter/package-lock.json"

    - run: npm ci
    - run: npm run lint:ci
    - run: npm run format:ci
