name: Makefile CI

on:
  push:
    branches: [ main, pthreads, openmp ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Download packages
      run: |
        sudo apt update
        sudo apt install build-essential gcc libomp-dev -y

    - name: Build project
      run: |
        make

    - name: Verify project
      run: |
        make verify
